// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TokenWarehouse.Infrastructure.Persistence;

#nullable disable

namespace TokenWarehouse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260822110000_HistoryOperationResults")]
    partial class HistoryOperationResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", b =>
                {
                    b.Property<string>("Ean13")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumptionModes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dlc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSearchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Packaging")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceHtCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Ean13");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.ArticleLifecycleHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ean13");

                    b.ToTable("ArticleLifecycleHistory");
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryDifference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousPhysicalStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultingPhysicalStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceOperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOperationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimestampUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ean13");

                    b.HasIndex("SourceOperationId")
                        .IsUnique();

                    b.ToTable("StockOperations", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockOperations_CountedQuantity_NonNegative", "CountedQuantity >= 0");

                            t.HasCheckConstraint("CK_StockOperations_CounterMovement_Fields", "Type <> 'COUNTER_MOVEMENT' OR (SourceOperationId IS NOT NULL AND length(trim(SourceOperationId)) > 0 AND SourceOperationType IS NOT NULL AND SourceOperationType IN ('SUPPLY', 'INVENTORY', 'SALE') AND Justification IS NOT NULL AND length(trim(Justification)) > 0)");

                            t.HasCheckConstraint("CK_StockOperations_InventoryDifference_Formula", "Type <> 'INVENTORY' OR InventoryDifference = CountedQuantity - PreviousPhysicalStock");

                            t.HasCheckConstraint("CK_StockOperations_PreviousPhysicalStock_NonNegative", "PreviousPhysicalStock >= 0");

                            t.HasCheckConstraint("CK_StockOperations_Quantity_Positive", "Type <> 'supply' OR Quantity > 0");

                            t.HasCheckConstraint("CK_StockOperations_ResultingPhysicalStock_Formula", "Type <> 'INVENTORY' OR ResultingPhysicalStock = CountedQuantity");

                            t.HasCheckConstraint("CK_StockOperations_ResultingPhysicalStock_NonNegative", "ResultingPhysicalStock >= 0");
                        });
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationLineEntity", b =>
                {
                    b.Property<string>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryDifference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InverseEffect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("INVENTORY");

                    b.Property<int>("PreviousPhysicalStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultingPhysicalStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceEffect")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationId", "LineNumber");

                    b.HasIndex("Ean13");

                    b.HasIndex("OperationId", "Ean13")
                        .IsUnique();

                    b.ToTable("StockOperationLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockOperationLines_CountedQuantity_NonNegative", "CountedQuantity >= 0");

                            t.HasCheckConstraint("CK_StockOperationLines_CounterMovement_Inverse", "OperationType <> 'COUNTER_MOVEMENT' OR InverseEffect = -SourceEffect");

                            t.HasCheckConstraint("CK_StockOperationLines_InventoryDifference_Formula", "OperationType <> 'INVENTORY' OR InventoryDifference = CountedQuantity - PreviousPhysicalStock");

                            t.HasCheckConstraint("CK_StockOperationLines_LineNumber_Positive", "LineNumber >= 1");

                            t.HasCheckConstraint("CK_StockOperationLines_OperationType_Valid", "OperationType IN ('supply', 'INVENTORY', 'SALE', 'COUNTER_MOVEMENT')");

                            t.HasCheckConstraint("CK_StockOperationLines_PreviousPhysicalStock_NonNegative", "PreviousPhysicalStock >= 0");

                            t.HasCheckConstraint("CK_StockOperationLines_Quantity_NonNegative", "Quantity >= 0");

                            t.HasCheckConstraint("CK_StockOperationLines_Quantity_PositiveForSupply", "OperationType <> 'supply' OR Quantity > 0");

                            t.HasCheckConstraint("CK_StockOperationLines_ResultingPhysicalStock_Formula", "OperationType <> 'INVENTORY' OR ResultingPhysicalStock = CountedQuantity");

                            t.HasCheckConstraint("CK_StockOperationLines_ResultingPhysicalStock_NonNegative", "ResultingPhysicalStock >= 0");
                        });
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockPositionEntity", b =>
                {
                    b.Property<string>("Ean13")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysicalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Ean13");

                    b.ToTable("StockPositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockPositions_PhysicalQuantity_NonNegative", "PhysicalQuantity >= 0");
                        });
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.ArticleLifecycleHistoryEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceOperationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationLineEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", "Operation")
                        .WithMany("Lines")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockPositionEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
