// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TokenWarehouse.Infrastructure.Persistence;

#nullable disable

namespace TokenWarehouse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260821173005_StockPositionVersion")]
    partial class StockPositionVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", b =>
                {
                    b.Property<string>("Ean13")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumptionModes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dlc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSearchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Packaging")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceHtCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Ean13");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.ArticleLifecycleHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NextStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ean13");

                    b.ToTable("ArticleLifecycleHistory");
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ean13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryDifference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviousPhysicalStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultingPhysicalStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimestampUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ean13");

                    b.ToTable("StockOperations", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockOperations_Quantity_Positive", "Type <> 'supply' OR Quantity > 0");

                            t.HasCheckConstraint("CK_StockOperations_CountedQuantity_NonNegative", "CountedQuantity >= 0");

                            t.HasCheckConstraint("CK_StockOperations_InventoryDifference_Formula", "InventoryDifference = CountedQuantity - PreviousPhysicalStock");

                            t.HasCheckConstraint("CK_StockOperations_PreviousPhysicalStock_NonNegative", "PreviousPhysicalStock >= 0");

                            t.HasCheckConstraint("CK_StockOperations_ResultingPhysicalStock_Formula", "ResultingPhysicalStock = CountedQuantity");

                            t.HasCheckConstraint("CK_StockOperations_ResultingPhysicalStock_NonNegative", "ResultingPhysicalStock >= 0");
                        });
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockPositionEntity", b =>
                {
                    b.Property<string>("Ean13")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysicalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Ean13");

                    b.ToTable("StockPositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockPositions_PhysicalQuantity_NonNegative", "PhysicalQuantity >= 0");
                        });
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.ArticleLifecycleHistoryEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockOperationEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TokenWarehouse.Infrastructure.Persistence.StockPositionEntity", b =>
                {
                    b.HasOne("TokenWarehouse.Infrastructure.Persistence.ArticleEntity", null)
                        .WithMany()
                        .HasForeignKey("Ean13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
